import 'package:shared_preferences/shared_preferences.dart';

class LanguageManager {
  static String _currentLanguage = 'en';

  static String get currentLanguage => _currentLanguage;

  static Future<void> loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString('language') ?? 'en';
  }

  static Future<void> setLanguage(String langCode) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language', langCode);
    _currentLanguage = langCode;
  }

  static String get(String key) {
    final map = _languages[_currentLanguage] ?? _languages['en']!;
    return map[key] ?? _languages['en']![key] ?? key;
  }

  static const Map<String, Map<String, String>> _languages = {
    // ─── ENGLISH ───────────────────────────────────────────
    'en': {
      'app_name': 'UdhaarBook',
      'tagline': 'Aapki Dukan, Aapka Hisaab',
      'total_udhaar': 'Total Udhaar',
      'add_customer': 'Add Customer',
      'customer_name': 'Customer Name',
      'phone_number': 'Phone Number (Optional)',
      'save': 'Save',
      'cancel': 'Cancel',
      'search_customer': 'Search customer...',
      'no_customers': 'No customers yet.\nTap + to add one!',
      'add_udhaar': 'Add Udhaar',
      'record_payment': 'Record Payment',
      'amount': 'Amount (₹)',
      'note': 'Note (Optional)',
      'date': 'Date',
      'pending': 'Pending',
      'cleared': 'Cleared',
      'transaction_history': 'Transaction History',
      'no_transactions': 'No transactions yet.',
      'whatsapp_reminder': 'WhatsApp Reminder',
      'whatsapp_message': 'Hello {name}, your pending udhaar at {store} is ₹{amount}. Please pay when convenient. Thank you.',
      'settings': 'Settings',
      'store_name': 'Store Name',
      'store_phone': 'Store Phone (Optional)',
      'language': 'Language',
      'export_csv': 'Export as CSV',
      'backup_data': 'Backup Data',
      'restore_data': 'Restore Backup',
      'clear_data': 'Clear All Data',
      'clear_data_confirm': 'Are you sure? This will delete everything!',
      'remove_ads': 'Remove Ads — ₹99',
      'upgrade_pro': 'Upgrade to Pro',
      'rate_us': 'Rate Us on Play Store',
      'share_app': 'Share App',
      'about': 'About',
      'version': 'Version',
      'general': 'General',
      'data': 'Data',
      'onboard_title_1': 'Add Customers Easily',
      'onboard_desc_1': 'Add your customers with name and phone number in seconds.',
      'onboard_title_2': 'Track Udhaar & Payments',
      'onboard_desc_2': 'Keep a clear record of every credit and payment.',
      'onboard_title_3': 'Send WhatsApp Reminders',
      'onboard_desc_3': 'Remind customers about pending udhaar in one tap.',
      'get_started': 'Get Started',
      'enter_store_name': 'Enter your store name',
      'store_name_hint': 'e.g. Sharma General Store',
      'continue_btn': 'Continue',
      'error_empty_name': 'Please enter customer name',
      'error_duplicate_name': 'Customer with this name already exists',
      'error_empty_amount': 'Please enter amount',
      'error_invalid_amount': 'Please enter valid amount',
      'error_store_name': 'Please enter your store name',
      'delete_customer': 'Delete Customer',
      'delete_confirm': 'This will delete customer and all transactions!',
      'yes_delete': 'Yes, Delete',
      'current_pending': 'Current Pending',
      'pro_title': 'UdhaarBook Pro',
      'pro_subtitle': 'Unlock all features',
      'free': 'Free',
      'pro': 'Pro',
      'buy_lifetime': 'Buy Lifetime — ₹299',
      'buy_yearly': 'Buy Yearly — ₹199/year',
    },

    // ─── HINDI ─────────────────────────────────────────────
    'hi': {
      'app_name': 'UdhaarBook',
      'tagline': 'आपकी दुकान, आपका हिसाब',
      'total_udhaar': 'कुल उधार',
      'add_customer': 'ग्राहक जोड़ें',
      'customer_name': 'ग्राहक का नाम',
      'phone_number': 'फोन नंबर (वैकल्पिक)',
      'save': 'सेव करें',
      'cancel': 'रद्द करें',
      'search_customer': 'ग्राहक खोजें...',
      'no_customers': 'कोई ग्राहक नहीं।\n+ दबाएं और जोड़ें!',
      'add_udhaar': 'उधार दें',
      'record_payment': 'भुगतान लें',
      'amount': 'राशि (₹)',
      'note': 'नोट (वैकल्पिक)',
      'date': 'तारीख',
      'pending': 'बाकी',
      'cleared': 'चुकता',
      'transaction_history': 'लेनदेन इतिहास',
      'no_transactions': 'कोई लेनदेन नहीं।',
      'whatsapp_reminder': 'WhatsApp रिमाइंडर',
      'whatsapp_message': 'नमस्ते {name} जी, {store} में आपका ₹{amount} उधार बाकी है। कृपया जल्द भुगतान करें। धन्यवाद।',
      'settings': 'सेटिंग्स',
      'store_name': 'दुकान का नाम',
      'store_phone': 'दुकान का फोन (वैकल्पिक)',
      'language': 'भाषा',
      'export_csv': 'CSV में निर्यात करें',
      'backup_data': 'डेटा बैकअप करें',
      'restore_data': 'बैकअप रिस्टोर करें',
      'clear_data': 'सारा डेटा मिटाएं',
      'clear_data_confirm': 'क्या आप निश्चित हैं? सब कुछ मिट जाएगा!',
      'remove_ads': 'विज्ञापन हटाएं — ₹99',
      'upgrade_pro': 'Pro में अपग्रेड करें',
      'rate_us': 'Play Store पर रेट करें',
      'share_app': 'ऐप शेयर करें',
      'about': 'जानकारी',
      'version': 'संस्करण',
      'general': 'सामान्य',
      'data': 'डेटा',
      'onboard_title_1': 'आसानी से ग्राहक जोड़ें',
      'onboard_desc_1': 'सेकंडों में नाम और फोन नंबर से ग्राहक जोड़ें।',
      'onboard_title_2': 'उधार और भुगतान ट्रैक करें',
      'onboard_desc_2': 'हर उधार और भुगतान का साफ रिकॉर्ड रखें।',
      'onboard_title_3': 'WhatsApp रिमाइंडर भेजें',
      'onboard_desc_3': 'एक टैप में ग्राहकों को बकाया उधार याद दिलाएं।',
      'get_started': 'शुरू करें',
      'enter_store_name': 'अपनी दुकान का नाम लिखें',
      'store_name_hint': 'जैसे: शर्मा जनरल स्टोर',
      'continue_btn': 'आगे बढ़ें',
      'error_empty_name': 'कृपया ग्राहक का नाम लिखें',
      'error_duplicate_name': 'इस नाम का ग्राहक पहले से है',
      'error_empty_amount': 'कृपया राशि लिखें',
      'error_invalid_amount': 'कृपया सही राशि लिखें',
      'error_store_name': 'कृपया दुकान का नाम लिखें',
      'delete_customer': 'ग्राहक मिटाएं',
      'delete_confirm': 'इससे ग्राहक और सभी लेनदेन मिट जाएंगे!',
      'yes_delete': 'हां, मिटाएं',
      'current_pending': 'अभी बाकी',
      'pro_title': 'UdhaarBook Pro',
      'pro_subtitle': 'सभी सुविधाएं अनलॉक करें',
      'free': 'मुफ्त',
      'pro': 'Pro',
      'buy_lifetime': 'लाइफटाइम खरीदें — ₹299',
      'buy_yearly': 'सालाना खरीदें — ₹199/साल',
    },

    // ─── MARATHI ───────────────────────────────────────────
    'mr': {
      'app_name': 'UdhaarBook',
      'tagline': 'आपली दुकान, आपला हिशेब',
      'total_udhaar': 'एकूण उधार',
      'add_customer': 'ग्राहक जोडा',
      'customer_name': 'ग्राहकाचे नाव',
      'phone_number': 'फोन नंबर (ऐच्छिक)',
      'save': 'सेव करा',
      'cancel': 'रद्द करा',
      'search_customer': 'ग्राहक शोधा...',
      'no_customers': 'अजून ग्राहक नाही.\n+ दाबा आणि जोडा!',
      'add_udhaar': 'उधार द्या',
      'record_payment': 'पेमेंट घ्या',
      'amount': 'रक्कम (₹)',
      'note': 'नोंद (ऐच्छिक)',
      'date': 'तारीख',
      'pending': 'बाकी',
      'cleared': 'चुकता',
      'transaction_history': 'व्यवहार इतिहास',
      'no_transactions': 'अजून व्यवहार नाही.',
      'whatsapp_reminder': 'WhatsApp रिमाइंडर',
      'whatsapp_message': 'नमस्कार {name}, {store} मध्ये तुमचे ₹{amount} उधार बाकी आहे. कृपया लवकर भरा. धन्यवाद.',
      'settings': 'सेटिंग्ज',
      'store_name': 'दुकानाचे नाव',
      'store_phone': 'दुकानाचा फोन (ऐच्छिक)',
      'language': 'भाषा',
      'export_csv': 'CSV मध्ये निर्यात करा',
      'backup_data': 'डेटा बॅकअप करा',
      'restore_data': 'बॅकअप रिस्टोर करा',
      'clear_data': 'सर्व डेटा मिटवा',
      'clear_data_confirm': 'खात्री आहे का? सर्व काही मिटेल!',
      'remove_ads': 'जाहिराती काढा — ₹99',
      'upgrade_pro': 'Pro मध्ये अपग्रेड करा',
      'rate_us': 'Play Store वर रेट करा',
      'share_app': 'अ‍ॅप शेअर करा',
      'about': 'माहिती',
      'version': 'आवृत्ती',
      'general': 'सामान्य',
      'data': 'डेटा',
      'onboard_title_1': 'सहज ग्राहक जोडा',
      'onboard_desc_1': 'काही सेकंदात नाव आणि फोन नंबरने ग्राहक जोडा।',
      'onboard_title_2': 'उधार आणि पेमेंट ट्रॅक करा',
      'onboard_desc_2': 'प्रत्येक उधार आणि पेमेंटची स्पष्ट नोंद ठेवा.',
      'onboard_title_3': 'WhatsApp रिमाइंडर पाठवा',
      'onboard_desc_3': 'एका टॅपमध्ये ग्राहकांना बाकी उधार आठवण करून द्या.',
      'get_started': 'सुरू करा',
      'enter_store_name': 'तुमच्या दुकानाचे नाव लिहा',
      'store_name_hint': 'उदा: शर्मा जनरल स्टोर',
      'continue_btn': 'पुढे जा',
      'error_empty_name': 'कृपया ग्राहकाचे नाव लिहा',
      'error_duplicate_name': 'या नावाचा ग्राहक आधीच आहे',
      'error_empty_amount': 'कृपया रक्कम लिहा',
      'error_invalid_amount': 'कृपया योग्य रक्कम लिहा',
      'error_store_name': 'कृपया दुकानाचे नाव लिहा',
      'delete_customer': 'ग्राहक मिटवा',
      'delete_confirm': 'यामुळे ग्राहक आणि सर्व व्यवहार मिटतील!',
      'yes_delete': 'हो, मिटवा',
      'current_pending': 'सध्या बाकी',
      'pro_title': 'UdhaarBook Pro',
      'pro_subtitle': 'सर्व सुविधा अनलॉक करा',
      'free': 'मोफत',
      'pro': 'Pro',
      'buy_lifetime': 'लाइफटाइम खरेदी करा — ₹299',
      'buy_yearly': 'वार्षिक खरेदी करा — ₹199/वर्ष',
    },
  };
}